/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : RFIDspi.c
**     Project     : K22_433MHz
**     Processor   : MK22FN1M0VLH12
**     Component   : GenericSWSPI
**     Version     : Component 01.024, Driver 01.15, CPU db: 3.00.000
**     Repository  : McuOnEclipse
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-02, 21:03, # CodeGen: 42
**     Abstract    :
**
**     Contents    :
**         RecvChar              - byte RFIDspi_RecvChar(byte *Chr);
**         SendChar              - byte RFIDspi_SendChar(byte val);
**         CharsInRxBuf          - byte RFIDspi_CharsInRxBuf(void);
**         CharsInTxBuf          - byte RFIDspi_CharsInTxBuf(void);
**         SetShiftClockPolarity - byte RFIDspi_SetShiftClockPolarity(byte Edge);
**         SetIdleClockPolarity  - byte RFIDspi_SetIdleClockPolarity(byte Level);
**         Write_ReadDummy       - void RFIDspi_Write_ReadDummy(byte val);
**         SetSlowMode           - void RFIDspi_SetSlowMode(void);
**         SetFastMode           - void RFIDspi_SetFastMode(void);
**
**     License : Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2014-2015, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implemented with using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file RFIDspi.c
** @version 01.15
** @brief
**
*/         
/*!
**  @addtogroup RFIDspi_module RFIDspi module documentation
**  @{
*/         


/* MODULE RFIDspi. */

#include "RFIDspi.h"

  /* data-clock-clock */

#define OVERRUN_ERR  0x01              /* Overrun error flag bit   */
#define CHAR_IN_RX   0x08              /* Char is in RX buffer     */

static byte RFIDspi_FastMode; /* 0: slow, 1: fast */
#define MOSI_IDLE_POLARITY    1        /* MOSI idle polarity is high */
#define CLOCK_IDLE_POLARITY   0        /* Clock idle polarity is low */

static byte CLKshift;
static byte CLKsampl;
static byte InputBuffer;
static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Unused */
                                       /*       5 - Unused */
                                       /*       6 - Unused */
                                       /*       7 - Unused */
#define RFIDspi_DELAY() \
    if (RFIDspi_FastMode) { /* we can change the speed at runtime */ \
      WAIT1_Waitus(1);                 /* delay for some cycles */ \
    } else { \
      WAIT1_Waitus(1);                 /* delay for some cycles */ \
    }
/*
** ===================================================================
**     Method      :  RFIDspi_SetFastMode (component GenericSWSPI)
**     Description :
**         Sets the fast mode
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void RFIDspi_SetFastMode(void)
{
  RFIDspi_FastMode = 1;
}

/*
** ===================================================================
**     Method      :  RFIDspi_SetSlowMode (component GenericSWSPI)
**     Description :
**         Changes to slow mode
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void RFIDspi_SetSlowMode(void)
{
  RFIDspi_FastMode = 0;
}

/*
** ===================================================================
**     Method      :  RFIDspi_RecvChar (component GenericSWSPI)
**     Description :
**         If any data received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_OVERRUN - Overrun error is detected
** ===================================================================
*/
byte RFIDspi_RecvChar(byte *Chr)
{
  if(!(SerFlag & CHAR_IN_RX)) {        /* Is char. received */
    return ERR_RXEMPTY;
  }
  *Chr = InputBuffer;                  /* Store the character */
  if(SerFlag&OVERRUN_ERR) {            /* Is "overrun" occurred? */
    SerFlag &= ~(OVERRUN_ERR|CHAR_IN_RX); /* If yes, clear flags */
    return ERR_OVERRUN;                /* ... and return error */
  } else {
    SerFlag &= ~CHAR_IN_RX;            /* If no, clear flag */
    return ERR_OK;                     /* ... and return */
  }
}

/*
** ===================================================================
**     Method      :  RFIDspi_Write_ReadDummy (component GenericSWSPI)
**     Description :
**         Writes to the bus, but does not read.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to put on the bus
**     Returns     : Nothing
** ===================================================================
*/
void RFIDspi_Write_ReadDummy(byte val)
{
  byte i;

  for(i=0; i<8; i++) {
    RFIDspi_DELAY();
    Output1_PutVal((bool)(val&128));   /* Set value on MOSI */
    InputBuffer <<= 1;
    RFIDspi_DELAY();
    Clock1_PutVal(CLKsampl);           /* Set CLK to sample value */
    val <<= 1;
    Clock1_PutVal(CLKshift);           /* Set CLK to shift value */
  }
  Output1_PutVal((bool)MOSI_IDLE_POLARITY); /* Set value on MOSI */
}

/*
** ===================================================================
**     Method      :  RFIDspi_SendChar (component GenericSWSPI)
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - Character to send.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte RFIDspi_SendChar(byte val)
{
  byte i;

  for(i=0; i<8; i++) {
    RFIDspi_DELAY();
    Output1_PutVal((bool)(val&128));   /* Set value on MOSI */
    InputBuffer <<= 1;
    RFIDspi_DELAY();
    Clock1_PutVal(CLKsampl);           /* Set CLK to sample value */
    InputBuffer |= Input1_GetVal()?1:0; /* Read value from MISO */
    val <<= 1;
    Clock1_PutVal(CLKshift);           /* Set CLK to shift value */
  }
  Output1_PutVal((bool)MOSI_IDLE_POLARITY); /* Set value on MOSI */
  if(SerFlag&CHAR_IN_RX) {             /* Is char. received? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set "overrun" flag */
  } else {
    SerFlag |= CHAR_IN_RX;             /* If no then set "char in Rx" flag */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  RFIDspi_CharsInRxBuf (component GenericSWSPI)
**     Description :
**         Returns number of characters in the input buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Returns number of characters in the input
**                           buffer.
** ===================================================================
*/
byte RFIDspi_CharsInRxBuf(void)
{
  return (byte)((SerFlag & CHAR_IN_RX)?(byte)1:(byte)0); /* Return number of chars in receive buffer */
}

/*
** ===================================================================
**     Method      :  RFIDspi_CharsInTxBuf (component GenericSWSPI)
**     Description :
**         Returns number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Returns number of characters in the output
**                           buffer.
** ===================================================================
*/
#if 0 /* implemented as macro in the header file */
byte RFIDspi_CharsInTxBuf(void)
{
  return 0;                            /* Return number of chars in transmit buffer */
}
#endif
/*
** ===================================================================
**     Method      :  RFIDspi_SetShiftClockPolarity (component GenericSWSPI)
**     Description :
**         Sets the shift clock polarity at runtime. Output data will
**         be shifted on the selected edge polarity.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Edge            - Edge polarity, possible values:
**                           0-falling edge,
**                           1-rising edge.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte RFIDspi_SetShiftClockPolarity(byte Edge)
{
  CLKshift = (byte)(Edge?(byte)1:(byte)0); /* Set shift value */
  CLKsampl = (byte)(CLKshift ^ (byte)0x01); /* Set sample value */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  RFIDspi_SetIdleClockPolarity (component GenericSWSPI)
**     Description :
**         Set the idle clock polarity at runtime. If communication
**         does not run, the clock signal will be set to the required
**         level.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Level           - Idle clock polarity:
**                           0-low
**                           1-high
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte RFIDspi_SetIdleClockPolarity(byte Level)
{
  Clock1_PutVal((byte)Level);          /* Set CLK to (new) idle value */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  RFIDspi_Init (component GenericSWSPI)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void RFIDspi_Init(void)
{
  RFIDspi_SetSlowMode();               /* slow mode is default */
  /* clock idle low, falling edge: Data - Sample - Shift */
  CLKsampl = 1;
  CLKshift = 0;
  Clock1_PutVal((bool)CLOCK_IDLE_POLARITY); /* Set CLK to idle value */
  Output1_PutVal((bool)MOSI_IDLE_POLARITY); /* Set value on MOSI */
  SerFlag = 0;                         /* Clear flags */
}


/* END RFIDspi. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/

