/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : rtTasks.h
**     CDE edition : Community
**     Project     : K22_433MHz
**     Processor   : MK22FN1M0VLH12
**     Component   : FreeRTOS_Tasks
**     Version     : Component 01.008, Driver 01.00, CPU db: 3.00.000
**     Repository  : McuOnEclipse
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-02, 21:03, # CodeGen: 42
**     Abstract    :
**
**     Settings    :
**          Component Name                                 : rtTasks
**          FreeRTOS                                       : FRTOS1
**          Number of tasks                                : 5
**            FreeRTOS task                                : _433MHzTask
**              Task name                                  : _433MHz
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 8
**            FreeRTOS task                                : _2_4GHzTask
**              Task name                                  : _2_4GHz
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 8
**            FreeRTOS task                                : GatewayTask
**              Task name                                  : Gateway
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 5
**            FreeRTOS task                                : InfoLEDTask
**              Task name                                  : InfoLED
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 10
**            FreeRTOS task                                : RFIDTaskTask
**              Task name                                  : RFIDTask
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 8
**     Contents    :
**         CreateTasks - void rtTasks_CreateTasks(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Omar Isa? Pinales Ayala, 2014, all rights reserved.
**     http      : http://www.mcuoneclipse.com
**     This an open source software driver for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file rtTasks.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup rtTasks_module rtTasks module documentation
**  @{
*/         

#ifndef __rtTasks_H
#define __rtTasks_H

/* MODULE rtTasks. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */
#include "FRTOS1.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif



/*
** ===================================================================
**     Method      :  rtTasks_CreateTasks (component FreeRTOS_Tasks)
**     Description :
**         Creates the tasks.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void rtTasks_CreateTasks(void);


#ifdef __cplusplus
}  /* extern "C" */
#endif
/* END rtTasks. */

#endif
/* ifndef __rtTasks_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
