/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : WAIT.h
**     Project     : SolderTermo
**     Processor   : MKE06Z128VLK4
**     Component   : Wait
**     Version     : Component 01.067, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-10-11, 12:18, # CodeGen: 31
**     Abstract    :
**          Implements busy waiting routines.
**     Settings    :
**          Component name                                 : WAIT
**          Manual Clock Values                            : Disabled
**          Delay100usFunction                             : Delay100US
**          RTOS                                           : Disabled
**          Watchdog                                       : Disabled
**     Contents    :
**         WAIT0Cycles   - void WAIT_WAIT0Cycles(void);
**         WAIT00Cycles  - void WAIT_WAIT00Cycles(void);
**         WaitCycles     - void WAIT_WaitCycles(uint16_t cycles);
**         WaitLongCycles - void WAIT_WaitLongCycles(uint32_t cycles);
**         Waitms         - void WAIT_Waitms(uint16_t ms);
**         Waitus         - void WAIT_Waitus(uint16_t us);
**         Waitns         - void WAIT_Waitns(uint16_t ns);
**         WaitOSms       - void WAIT_WaitOSms(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2014, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing waiting routines using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file WAIT.h
** @version 01.00
** @brief
**          Implements busy waiting routines.
*/         
/*!
**  @addtogroup WAIT_module WAIT module documentation
**  @{
*/         

#ifndef __WAIT_H
#define __WAIT_H

/* MODULE WAIT. */

/* Include shared modules, which are used for whole project */
#include "common.h"
#include "ke06_config.h"

#ifdef __cplusplus
extern "C" {
#endif


#define WAIT_INSTR_CLOCK_HZ       CPU_CORE_CLK_HZ /* for Kinetis, use core clock as base for instruction execution */
#define WAIT_NofCyclesMs(ms, hz)  ((ms)*((hz)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define WAIT_NofCyclesUs(us, hz)  ((us)*(((hz)/1000)/1000)) /* calculates the needed cycles based on bus clock frequency */
#define WAIT_NofCyclesNs(ns, hz)  (((ns)*(((hz)/1000)/1000))/1000) /* calculates the needed cycles based on bus clock frequency */


#define WAIT_WAIT_C(cycles) \
     ( (cycles)<=10 ? \
          WAIT_WAIT0Cycles() \
        : WAIT_WaitCycles((uint16_t)cycles) \
      )                                      /*!< wait for some cycles */


void WAIT_WAIT0Cycles(void);
/*
** ===================================================================
**     Method      :  WAIT_WAIT0Cycles (component Wait)
**     Description :
**         Wait for 10 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void WAIT_WAIT00Cycles(void);
/*
** ===================================================================
**     Method      :  WAIT_WAIT00Cycles (component Wait)
**     Description :
**         Wait for 100 CPU cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void WAIT_WaitCycles(uint16_t cycles);
/*
** ===================================================================
**     Method      :  WAIT_WaitCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (16bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

void WAIT_Waitms(uint16_t ms);
/*
** ===================================================================
**     Method      :  WAIT_Waitms (component Wait)
**     Description :
**         Wait for a specified time in milliseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ms              - How many milliseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define WAIT_Waitus(us)  \
       (  ((WAIT_NofCyclesUs((us),WAIT_INSTR_CLOCK_HZ)==0)||(us)==0) ? \
          (void)0 : \
          ( ((us)/1000)==0 ? (void)0 : WAIT_Waitms((uint16_t)((us)/1000))) \
          , (WAIT_NofCyclesUs(((us)%1000), WAIT_INSTR_CLOCK_HZ)==0) ? (void)0 : \
            WAIT_WAIT_C(WAIT_NofCyclesUs(((us)%1000), WAIT_INSTR_CLOCK_HZ)) \
       )
/*
** ===================================================================
**     Method      :  WAIT_Waitus (component Wait)
**     Description :
**         Wait for a specified time in microseconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us              - How many microseconds the function has to
**                           wait
**     Returns     : Nothing
** ===================================================================
*/

/* we are having a static clock configuration: implement as macro/inlined version */
#define WAIT_Waitns(ns)  \
       (  ((WAIT_NofCyclesNs((ns), WAIT_INSTR_CLOCK_HZ)==0)||(ns)==0) ? \
          (void)0 : \
          WAIT_Waitus((ns)/1000) \
          , (WAIT_NofCyclesNs((ns)%1000, WAIT_INSTR_CLOCK_HZ)==0) ? \
              (void)0 : \
              WAIT_WAIT_C(WAIT_NofCyclesNs(((ns)%1000), WAIT_INSTR_CLOCK_HZ)) \
       )
/*
** ===================================================================
**     Method      :  WAIT_Waitns (component Wait)
**     Description :
**         Wait for a specified time in nano seconds.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ns              - How many ns the function has to wait
**     Returns     : Nothing
** ===================================================================
*/

#define WAIT_WaitOSms(ms) \
  WAIT_Waitms(ms) /* no RTOS used, so use normal wait */
/*
** ===================================================================
**     Method      :  WAIT_WaitOSms (component Wait)
**     Description :
**         If an RTOS is enabled, this routine will use a non-blocking
**         wait method. Otherwise it will do a busy/blocking wait.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#ifdef __cplusplus
}  /* extern "C" */
#endif

void WAIT_WaitLongCycles(uint32_t cycles);
/*
** ===================================================================
**     Method      :  WAIT_WaitLongCycles (component Wait)
**     Description :
**         Wait for a specified number of CPU cycles (32bit data type).
**     Parameters  :
**         NAME            - DESCRIPTION
**         cycles          - The number of cycles to wait.
**     Returns     : Nothing
** ===================================================================
*/

/* END WAIT. */

#endif
/* ifndef __WAIT_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
